### ISSUE TITLE
Supported?

### ISSUE THREAD

**Issue by cpgb85** [licson/libSSE-php#34]
is this no longer supported?

**Comment by licson0729** [comment]
Although not actively developed, this is still supported. If you have any questions please feel free to ask.

**Comment by svikramjeet** [comment]
@licson0729 : I have tried this on local and it is working fine but throwing 503 request timeout on heroku/GCP.

**Comment by licson0729** [comment]
> @licson0729 : I have tried this on local and it is working fine but throwing 503 request timeout on heroku/GCP.

PaaS platform like Heroku may have request buffering and/or script execution time limits that prevented long HTTP requests to finish which is a
